services:
  ogn-server:
    build: .
    container_name: xcsoar-ogn-server
    volumes:
      - ./names.csv:/app/names.csv
      - ./serverdata.txt:/app/serverdata.txt
      - ./private.key:/app/private.key
      - ./adminChat.id:/app/adminChat.id
      - ./location.txt:/app/location.txt
      - ./igc_files:/app/igc_files
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1